### ISSUE TITLE
@angular/upgrade/static compatible

### ISSUE THREAD

**Issue by prasannapattam** [ui-router/angular-hybrid#26] opened 2017-01-09 02:04 UTC
Is the hybrid setup compatible with the new upgrade module (@angular/upgrade/static). Please provide a sample or directions.

**Comment by christopherthielen** [comment] 2017-01-11 19:54
I'm working on ng2 in the coming week or two.  Once I've released ui-router-ng2 `1.0.0-beta.4` I'll work on updating `ng1-to-ng2` codebase.

**Comment by trumbitta** [comment] 2017-01-18 16:02
Duplicate of #24 ? :)

**Comment by mischkl** [comment] 2017-02-22 12:18
Any news on this front?

**Comment by vladtar** [comment] 2017-02-22 19:04
+1

**Comment by agent613** [comment] 2017-03-10 16:14
Any update on this?  It doesn't seem possible to use AOT until this is resolved.

**Comment by RaphyLi** [comment] 2017-04-21 08:38
@christopherthielen Any update on this?

**Comment by christopherthielen** [comment] 2017-05-15 18:20
I think this should be ready soon.  I'm stealing [the work that @jonrimmer did](https://github.com/ui-router/angular-hybrid/issues/24#issuecomment-265029379) back in December.  (thanks Jon!)

**Comment by christopherthielen** [comment] 2017-05-16 18:38
This is released as `@uirouter/angular-hybrid` version 3.0.1

**Closed by christopherthielen** 2017-05-16 18:38 UTC
